/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPresetsRouteImport } from './routes/_authenticated/presets'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfigureRouteImport } from './routes/_authenticated/configure'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSchedulesIndexRouteImport } from './routes/_authenticated/schedules.index'
import { Route as AuthenticatedExecutionsIndexRouteImport } from './routes/_authenticated/executions.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedSchedulesScheduleIdRouteImport } from './routes/_authenticated/schedules.$scheduleId'
import { Route as AuthenticatedExecutionsJobIdRouteImport } from './routes/_authenticated/executions.$jobId'
import { Route as AuthenticatedConfigureFableIdRouteImport } from './routes/_authenticated/configure.$fableId'
import { Route as AuthenticatedAdminVariablesRouteImport } from './routes/_authenticated/admin/variables'
import { Route as AuthenticatedAdminPluginsRouteImport } from './routes/_authenticated/admin/plugins'
import { Route as AuthenticatedAdminArtifactsRouteImport } from './routes/_authenticated/admin/artifacts'
import { Route as AuthenticatedAdminVariablesIndexRouteImport } from './routes/_authenticated/admin/variables.index'
import { Route as AuthenticatedAdminPluginsIndexRouteImport } from './routes/_authenticated/admin/plugins.index'
import { Route as AuthenticatedAdminArtifactsIndexRouteImport } from './routes/_authenticated/admin/artifacts.index'
import { Route as AuthenticatedAdminPluginsPluginIdRouteImport } from './routes/_authenticated/admin/plugins.$pluginId'
import { Route as AuthenticatedAdminArtifactsArtifactIdRouteImport } from './routes/_authenticated/admin/artifacts.$artifactId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPresetsRoute = AuthenticatedPresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfigureRoute = AuthenticatedConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSchedulesIndexRoute =
  AuthenticatedSchedulesIndexRouteImport.update({
    id: '/schedules/',
    path: '/schedules/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExecutionsIndexRoute =
  AuthenticatedExecutionsIndexRouteImport.update({
    id: '/executions/',
    path: '/executions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSchedulesScheduleIdRoute =
  AuthenticatedSchedulesScheduleIdRouteImport.update({
    id: '/schedules/$scheduleId',
    path: '/schedules/$scheduleId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExecutionsJobIdRoute =
  AuthenticatedExecutionsJobIdRouteImport.update({
    id: '/executions/$jobId',
    path: '/executions/$jobId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfigureFableIdRoute =
  AuthenticatedConfigureFableIdRouteImport.update({
    id: '/$fableId',
    path: '/$fableId',
    getParentRoute: () => AuthenticatedConfigureRoute,
  } as any)
const AuthenticatedAdminVariablesRoute =
  AuthenticatedAdminVariablesRouteImport.update({
    id: '/variables',
    path: '/variables',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPluginsRoute =
  AuthenticatedAdminPluginsRouteImport.update({
    id: '/plugins',
    path: '/plugins',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminArtifactsRoute =
  AuthenticatedAdminArtifactsRouteImport.update({
    id: '/artifacts',
    path: '/artifacts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVariablesIndexRoute =
  AuthenticatedAdminVariablesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminVariablesRoute,
  } as any)
const AuthenticatedAdminPluginsIndexRoute =
  AuthenticatedAdminPluginsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminPluginsRoute,
  } as any)
const AuthenticatedAdminArtifactsIndexRoute =
  AuthenticatedAdminArtifactsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminArtifactsRoute,
  } as any)
const AuthenticatedAdminPluginsPluginIdRoute =
  AuthenticatedAdminPluginsPluginIdRouteImport.update({
    id: '/$pluginId',
    path: '/$pluginId',
    getParentRoute: () => AuthenticatedAdminPluginsRoute,
  } as any)
const AuthenticatedAdminArtifactsArtifactIdRoute =
  AuthenticatedAdminArtifactsArtifactIdRouteImport.update({
    id: '/$artifactId',
    path: '/$artifactId',
    getParentRoute: () => AuthenticatedAdminArtifactsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/configure': typeof AuthenticatedConfigureRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/presets': typeof AuthenticatedPresetsRoute
  '/admin/artifacts': typeof AuthenticatedAdminArtifactsRouteWithChildren
  '/admin/plugins': typeof AuthenticatedAdminPluginsRouteWithChildren
  '/admin/variables': typeof AuthenticatedAdminVariablesRouteWithChildren
  '/configure/$fableId': typeof AuthenticatedConfigureFableIdRoute
  '/executions/$jobId': typeof AuthenticatedExecutionsJobIdRoute
  '/schedules/$scheduleId': typeof AuthenticatedSchedulesScheduleIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/executions/': typeof AuthenticatedExecutionsIndexRoute
  '/schedules/': typeof AuthenticatedSchedulesIndexRoute
  '/admin/artifacts/$artifactId': typeof AuthenticatedAdminArtifactsArtifactIdRoute
  '/admin/plugins/$pluginId': typeof AuthenticatedAdminPluginsPluginIdRoute
  '/admin/artifacts/': typeof AuthenticatedAdminArtifactsIndexRoute
  '/admin/plugins/': typeof AuthenticatedAdminPluginsIndexRoute
  '/admin/variables/': typeof AuthenticatedAdminVariablesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/configure': typeof AuthenticatedConfigureRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/presets': typeof AuthenticatedPresetsRoute
  '/configure/$fableId': typeof AuthenticatedConfigureFableIdRoute
  '/executions/$jobId': typeof AuthenticatedExecutionsJobIdRoute
  '/schedules/$scheduleId': typeof AuthenticatedSchedulesScheduleIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/executions': typeof AuthenticatedExecutionsIndexRoute
  '/schedules': typeof AuthenticatedSchedulesIndexRoute
  '/admin/artifacts/$artifactId': typeof AuthenticatedAdminArtifactsArtifactIdRoute
  '/admin/plugins/$pluginId': typeof AuthenticatedAdminPluginsPluginIdRoute
  '/admin/artifacts': typeof AuthenticatedAdminArtifactsIndexRoute
  '/admin/plugins': typeof AuthenticatedAdminPluginsIndexRoute
  '/admin/variables': typeof AuthenticatedAdminVariablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/configure': typeof AuthenticatedConfigureRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/presets': typeof AuthenticatedPresetsRoute
  '/_authenticated/admin/artifacts': typeof AuthenticatedAdminArtifactsRouteWithChildren
  '/_authenticated/admin/plugins': typeof AuthenticatedAdminPluginsRouteWithChildren
  '/_authenticated/admin/variables': typeof AuthenticatedAdminVariablesRouteWithChildren
  '/_authenticated/configure/$fableId': typeof AuthenticatedConfigureFableIdRoute
  '/_authenticated/executions/$jobId': typeof AuthenticatedExecutionsJobIdRoute
  '/_authenticated/schedules/$scheduleId': typeof AuthenticatedSchedulesScheduleIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/executions/': typeof AuthenticatedExecutionsIndexRoute
  '/_authenticated/schedules/': typeof AuthenticatedSchedulesIndexRoute
  '/_authenticated/admin/artifacts/$artifactId': typeof AuthenticatedAdminArtifactsArtifactIdRoute
  '/_authenticated/admin/plugins/$pluginId': typeof AuthenticatedAdminPluginsPluginIdRoute
  '/_authenticated/admin/artifacts/': typeof AuthenticatedAdminArtifactsIndexRoute
  '/_authenticated/admin/plugins/': typeof AuthenticatedAdminPluginsIndexRoute
  '/_authenticated/admin/variables/': typeof AuthenticatedAdminVariablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/configure'
    | '/dashboard'
    | '/presets'
    | '/admin/artifacts'
    | '/admin/plugins'
    | '/admin/variables'
    | '/configure/$fableId'
    | '/executions/$jobId'
    | '/schedules/$scheduleId'
    | '/admin/'
    | '/executions/'
    | '/schedules/'
    | '/admin/artifacts/$artifactId'
    | '/admin/plugins/$pluginId'
    | '/admin/artifacts/'
    | '/admin/plugins/'
    | '/admin/variables/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/configure'
    | '/dashboard'
    | '/presets'
    | '/configure/$fableId'
    | '/executions/$jobId'
    | '/schedules/$scheduleId'
    | '/admin'
    | '/executions'
    | '/schedules'
    | '/admin/artifacts/$artifactId'
    | '/admin/plugins/$pluginId'
    | '/admin/artifacts'
    | '/admin/plugins'
    | '/admin/variables'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/_authenticated/admin'
    | '/_authenticated/configure'
    | '/_authenticated/dashboard'
    | '/_authenticated/presets'
    | '/_authenticated/admin/artifacts'
    | '/_authenticated/admin/plugins'
    | '/_authenticated/admin/variables'
    | '/_authenticated/configure/$fableId'
    | '/_authenticated/executions/$jobId'
    | '/_authenticated/schedules/$scheduleId'
    | '/_authenticated/admin/'
    | '/_authenticated/executions/'
    | '/_authenticated/schedules/'
    | '/_authenticated/admin/artifacts/$artifactId'
    | '/_authenticated/admin/plugins/$pluginId'
    | '/_authenticated/admin/artifacts/'
    | '/_authenticated/admin/plugins/'
    | '/_authenticated/admin/variables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/presets': {
      id: '/_authenticated/presets'
      path: '/presets'
      fullPath: '/presets'
      preLoaderRoute: typeof AuthenticatedPresetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configure': {
      id: '/_authenticated/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof AuthenticatedConfigureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedules/': {
      id: '/_authenticated/schedules/'
      path: '/schedules'
      fullPath: '/schedules/'
      preLoaderRoute: typeof AuthenticatedSchedulesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/executions/': {
      id: '/_authenticated/executions/'
      path: '/executions'
      fullPath: '/executions/'
      preLoaderRoute: typeof AuthenticatedExecutionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/schedules/$scheduleId': {
      id: '/_authenticated/schedules/$scheduleId'
      path: '/schedules/$scheduleId'
      fullPath: '/schedules/$scheduleId'
      preLoaderRoute: typeof AuthenticatedSchedulesScheduleIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/executions/$jobId': {
      id: '/_authenticated/executions/$jobId'
      path: '/executions/$jobId'
      fullPath: '/executions/$jobId'
      preLoaderRoute: typeof AuthenticatedExecutionsJobIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configure/$fableId': {
      id: '/_authenticated/configure/$fableId'
      path: '/$fableId'
      fullPath: '/configure/$fableId'
      preLoaderRoute: typeof AuthenticatedConfigureFableIdRouteImport
      parentRoute: typeof AuthenticatedConfigureRoute
    }
    '/_authenticated/admin/variables': {
      id: '/_authenticated/admin/variables'
      path: '/variables'
      fullPath: '/admin/variables'
      preLoaderRoute: typeof AuthenticatedAdminVariablesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plugins': {
      id: '/_authenticated/admin/plugins'
      path: '/plugins'
      fullPath: '/admin/plugins'
      preLoaderRoute: typeof AuthenticatedAdminPluginsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/artifacts': {
      id: '/_authenticated/admin/artifacts'
      path: '/artifacts'
      fullPath: '/admin/artifacts'
      preLoaderRoute: typeof AuthenticatedAdminArtifactsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/variables/': {
      id: '/_authenticated/admin/variables/'
      path: '/'
      fullPath: '/admin/variables/'
      preLoaderRoute: typeof AuthenticatedAdminVariablesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminVariablesRoute
    }
    '/_authenticated/admin/plugins/': {
      id: '/_authenticated/admin/plugins/'
      path: '/'
      fullPath: '/admin/plugins/'
      preLoaderRoute: typeof AuthenticatedAdminPluginsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminPluginsRoute
    }
    '/_authenticated/admin/artifacts/': {
      id: '/_authenticated/admin/artifacts/'
      path: '/'
      fullPath: '/admin/artifacts/'
      preLoaderRoute: typeof AuthenticatedAdminArtifactsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminArtifactsRoute
    }
    '/_authenticated/admin/plugins/$pluginId': {
      id: '/_authenticated/admin/plugins/$pluginId'
      path: '/$pluginId'
      fullPath: '/admin/plugins/$pluginId'
      preLoaderRoute: typeof AuthenticatedAdminPluginsPluginIdRouteImport
      parentRoute: typeof AuthenticatedAdminPluginsRoute
    }
    '/_authenticated/admin/artifacts/$artifactId': {
      id: '/_authenticated/admin/artifacts/$artifactId'
      path: '/$artifactId'
      fullPath: '/admin/artifacts/$artifactId'
      preLoaderRoute: typeof AuthenticatedAdminArtifactsArtifactIdRouteImport
      parentRoute: typeof AuthenticatedAdminArtifactsRoute
    }
  }
}

interface AuthenticatedAdminArtifactsRouteChildren {
  AuthenticatedAdminArtifactsArtifactIdRoute: typeof AuthenticatedAdminArtifactsArtifactIdRoute
  AuthenticatedAdminArtifactsIndexRoute: typeof AuthenticatedAdminArtifactsIndexRoute
}

const AuthenticatedAdminArtifactsRouteChildren: AuthenticatedAdminArtifactsRouteChildren =
  {
    AuthenticatedAdminArtifactsArtifactIdRoute:
      AuthenticatedAdminArtifactsArtifactIdRoute,
    AuthenticatedAdminArtifactsIndexRoute:
      AuthenticatedAdminArtifactsIndexRoute,
  }

const AuthenticatedAdminArtifactsRouteWithChildren =
  AuthenticatedAdminArtifactsRoute._addFileChildren(
    AuthenticatedAdminArtifactsRouteChildren,
  )

interface AuthenticatedAdminPluginsRouteChildren {
  AuthenticatedAdminPluginsPluginIdRoute: typeof AuthenticatedAdminPluginsPluginIdRoute
  AuthenticatedAdminPluginsIndexRoute: typeof AuthenticatedAdminPluginsIndexRoute
}

const AuthenticatedAdminPluginsRouteChildren: AuthenticatedAdminPluginsRouteChildren =
  {
    AuthenticatedAdminPluginsPluginIdRoute:
      AuthenticatedAdminPluginsPluginIdRoute,
    AuthenticatedAdminPluginsIndexRoute: AuthenticatedAdminPluginsIndexRoute,
  }

const AuthenticatedAdminPluginsRouteWithChildren =
  AuthenticatedAdminPluginsRoute._addFileChildren(
    AuthenticatedAdminPluginsRouteChildren,
  )

interface AuthenticatedAdminVariablesRouteChildren {
  AuthenticatedAdminVariablesIndexRoute: typeof AuthenticatedAdminVariablesIndexRoute
}

const AuthenticatedAdminVariablesRouteChildren: AuthenticatedAdminVariablesRouteChildren =
  {
    AuthenticatedAdminVariablesIndexRoute:
      AuthenticatedAdminVariablesIndexRoute,
  }

const AuthenticatedAdminVariablesRouteWithChildren =
  AuthenticatedAdminVariablesRoute._addFileChildren(
    AuthenticatedAdminVariablesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminArtifactsRoute: typeof AuthenticatedAdminArtifactsRouteWithChildren
  AuthenticatedAdminPluginsRoute: typeof AuthenticatedAdminPluginsRouteWithChildren
  AuthenticatedAdminVariablesRoute: typeof AuthenticatedAdminVariablesRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminArtifactsRoute:
    AuthenticatedAdminArtifactsRouteWithChildren,
  AuthenticatedAdminPluginsRoute: AuthenticatedAdminPluginsRouteWithChildren,
  AuthenticatedAdminVariablesRoute:
    AuthenticatedAdminVariablesRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedConfigureRouteChildren {
  AuthenticatedConfigureFableIdRoute: typeof AuthenticatedConfigureFableIdRoute
}

const AuthenticatedConfigureRouteChildren: AuthenticatedConfigureRouteChildren =
  {
    AuthenticatedConfigureFableIdRoute: AuthenticatedConfigureFableIdRoute,
  }

const AuthenticatedConfigureRouteWithChildren =
  AuthenticatedConfigureRoute._addFileChildren(
    AuthenticatedConfigureRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedConfigureRoute: typeof AuthenticatedConfigureRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPresetsRoute: typeof AuthenticatedPresetsRoute
  AuthenticatedExecutionsJobIdRoute: typeof AuthenticatedExecutionsJobIdRoute
  AuthenticatedSchedulesScheduleIdRoute: typeof AuthenticatedSchedulesScheduleIdRoute
  AuthenticatedExecutionsIndexRoute: typeof AuthenticatedExecutionsIndexRoute
  AuthenticatedSchedulesIndexRoute: typeof AuthenticatedSchedulesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedConfigureRoute: AuthenticatedConfigureRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPresetsRoute: AuthenticatedPresetsRoute,
  AuthenticatedExecutionsJobIdRoute: AuthenticatedExecutionsJobIdRoute,
  AuthenticatedSchedulesScheduleIdRoute: AuthenticatedSchedulesScheduleIdRoute,
  AuthenticatedExecutionsIndexRoute: AuthenticatedExecutionsIndexRoute,
  AuthenticatedSchedulesIndexRoute: AuthenticatedSchedulesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
